version: "3"

services:
  app:
    container_name: gh_archive_analysis
    image: gh_archive_analysis:latest
    build: .
    restart: on-failure
    volumes:
      - ./gh_archive_csv/:/usr/src/app/gh_archive_csv/
      - ./gh_archive_zip_files/:/usr/src/app/gh_archive_zip_files/
